name: Publish Docker image

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: "my-company-demo.stage.cr.de-txl.ionos.com"
  REPO_TAG: "my-company-demo.stage.cr.de-txl.ionos.com/hello-world:latest"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to our registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REPO_TAG }}